# Generated by Django 4.2 on 2023-04-21 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Клиент')),
                ('adress', models.TextField(verbose_name='Адрес клиента')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Особенности клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Товар')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Поступило')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sklad.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('-published',),
            },
        ),
    ]
