# Generated by Django 4.2 on 2023-04-21 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovar',
            name='client',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата заказа')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.client', verbose_name='Клиент')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.tovar', verbose_name='Товар')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='order_1',
            field=models.ManyToManyField(through='sklad.Order', to='sklad.tovar'),
        ),
    ]
