# Generated by Django 4.2 on 2023-04-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0002_remove_tovar_client_order_client_order_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-published',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
